name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-paths:
          - { service: frontend, path: frontend }
          - { service: backend-user-management-service, path: backend/user-management-service }
          - { service: backend-package-management-service, path: backend/package-management-service }
          - { service: backend-reservation-service, path: backend/reservation-service }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t silviu1409/${{ matrix.service-paths.service }}:${{ github.sha }} ${{ matrix.service-paths.path }}
          docker tag silviu1409/${{ matrix.service-paths.service }}:${{ github.sha }} silviu1409/${{ matrix.service-paths.service }}:latest
          docker push silviu1409/${{ matrix.service-paths.service }}:${{ github.sha }}
          docker push silviu1409/${{ matrix.service-paths.service }}:latest
