name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker Images to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server-ip "
            docker pull my-dockerhub-user/frontend:latest &&
            docker pull my-dockerhub-user/user-management-service:latest &&
            docker pull my-dockerhub-user/package-management-service:latest &&
            docker pull my-dockerhub-user/reservation-service:latest &&
            docker-compose -f /path/to/your/docker-compose.yml up -d
          "
